
<SelectionTool>:
    orientation: "vertical"

    book_selector: _book_selector
    page_selector: _page_selector
    image_pane: _image_pane
    # word_list: _word_list

    book_id: self.book_selector.text
    page: self.page_selector.text

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 16
        # BoxLayout:
        #     id: _word_list
        #     size_hint_x: 0
        #     orientation: 'vertical'

        ImagePane:
            id: _image_pane
            size_hint_x: 1
            source: ''

    BoxLayout:
        orientation: 'horizontal'
        Label:  
            size_hint: 0.9, 0.4
            pos_hint:{'center_x':0.3, 'y':0} 
        Button:
            background_color: (0,0,0,0)
            canvas:
                Color:
                    rgba: 1, 1, 1, 1
                Rectangle:
                    pos:self.pos
                    size:self.size
                    source:'clear.png'
            size_hint: 2, 1.5
            pos_hint:{'center_x':0.3, 'y':-0.3} 
            text: "Delete"
            on_press: root.image_pane.delete_last_rectangle()

        Label:  
            size_hint: 0.9, 0.4
        Button:
            background_color: (0,0,0,0)
            canvas:
                Color:
                    rgba: 1, 1, 1, 1
                Rectangle:
                    pos:self.pos
                    size:self.size
                    source:'save1.png'
            size_hint: 2, 1.5
            pos_hint:{'center_x':0.3, 'y':-0.3} 
            text: "Save"
            on_press: root.Ss()
        Label:  
            size_hint: 0.9, 0.4
        Spinner:
            id: _book_selector

        Spinner:
            id: _page_selector